apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vllm-qwen-qwe-6986e55e-wen3-14b
  namespace: kalantar-3
  labels:
spec:
  selector:
    matchLabels:
      llm-d.ai/inferenceServing: "true"
      llm-d.ai/model: qwen-qwe-6986e55e-wen3-14b
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    interval: 30s
